error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:00:11.583Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:00:31.389Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:01:36.622Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:01:45.538Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:01:52.336Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:07:38.558Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:07:38.736Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:13:56.345Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:13:56.622Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:14:02.550Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:14:02.789Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:14:29.178Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:14:29.425Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:15:05.240Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:15:05.498Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:18:34.434Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:18:34.547Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:19:15.401Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:19:15.517Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:20:19.028Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:20:19.153Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:20:23.885Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:20:23.998Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:20:49.220Z"}
error: Could not connect to the database. password authentication failed for user "MILIND" {"name":"SequelizeConnectionError","original":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"parent":{"code":"28P01","file":"auth.c","length":102,"line":"324","name":"error","routine":"auth_failed","severity":"FATAL"},"stack":"SequelizeConnectionError: password authentication failed for user \"MILIND\"\n    at Client._connectionCallback (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\sequelize\\src\\dialects\\postgres\\connection-manager.js:196:24)\n    at Client._handleErrorWhileConnecting (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:336:19)\n    at Client._handleErrorMessage (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\client.js:356:19)\n    at Connection.emit (node:events:524:28)\n    at Connection.emit (node:domain:489:12)\n    at C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg\\lib\\connection.js:116:12\n    at Parser.parse (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\parser.ts:103:9)\n    at Socket.<anonymous> (C:\\Users\\PratikBagul\\NodeJsProjects\\FundooNotes_Backend\\node_modules\\pg-protocol\\src\\index.ts:7:48)\n    at Socket.emit (node:events:524:28)\n    at Socket.emit (node:domain:489:12)\n    at addChunk (node:internal/streams/readable:561:12)\n    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n    at Socket.Readable.push (node:internal/streams/readable:392:5)\n    at TCP.onStreamRead (node:internal/stream_base_commons:189:23)","timestamp":"2025-05-20T09:20:49.343Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:22:57.126Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:22:57.473Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:24:29.372Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:24:29.628Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at createStrictSyntaxError (C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\body-parser\lib\types\json.js:169:10)
    at parse (C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\body-parser\lib\types\json.js:86:15)
    at C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:211:14)
    at invokeCallback (C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\raw-body\index.js:238:16)
    at done (C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\raw-body\index.js:227:7)
    at IncomingMessage.onEnd (C:\Users\PratikBagul\NodeJsProjects\FundooNotes_Backend\node_modules\raw-body\index.js:287:7)
    at IncomingMessage.emit (node:events:524:28)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at processTicksAndRejections (node:internal/process/task_queues:90:21) 
    url - /api/v1/ 
    method - GET 
    IP - ::1
   {"timestamp":"2025-05-20T09:26:06.553Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:26:40.257Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:26:40.564Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:28:56.932Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:28:57.200Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:29:10.535Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:29:10.755Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:30:03.372Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:30:03.651Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:31:19.085Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:31:19.321Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:33:53.751Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:33:54.136Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:35:15.698Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:35:15.980Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:37:34.933Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:37:35.281Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:37:47.948Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:37:48.194Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:38:51.934Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:38:52.188Z"}
info: Server started at http://localhost:5000/api/v1/ {"timestamp":"2025-05-20T09:40:25.727Z"}
info: Connected to the database. {"timestamp":"2025-05-20T09:40:26.021Z"}
